# Generated by Django 5.1.2 on 2025-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_espace', models.CharField(choices=[('petite_salle', 'Petite salle'), ('moyenne_salle', 'Moyenne salle'), ('grande_salle', 'Grande salle'), ('reunion', 'Salle de réunion'), ('brainstorming', 'Salle de brainstorming'), ('studio', 'Salle de studio'), ('espace_detente', 'Espace détente')], max_length=50)),
                ('capacite', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('equipements', models.TextField(blank=True, help_text='Liste des équipements (Wi-Fi, projecteur, etc.)')),
                ('prix_par_heure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='espaces/')),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
