# Generated by Django 5.1.2 on 2025-11-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='espaces/')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client.espace')),
            ],
        ),
    ]
