# Generated by Django 5.1.2 on 2025-12-08 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_activesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='espace',
            name='equipements',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_four', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('AMEX', 'AMEX'), ('Discover', 'Discover'), ('JCB', 'JCB'), ('Diners', 'Diners'), ('UnionPay', 'UnionPay'), ('CB', 'CB')], max_length=20)),
                ('expiry', models.CharField(max_length=5)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='default_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.paymentcard'),
        ),
    ]
