# Generated by Django 5.1.2 on 2025-12-09 00:08
from datetime import date, time
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0006_reservation'),
    ]
    
    operations = [
        # 1️⃣ Supprimer temporairement l'ancien unique_together
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        
        # 2️⃣ Ajouter les nouveaux champs avec des valeurs par défaut
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=date.today),  # ✅ Correct
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_debut',
            field=models.TimeField(default=time(9, 0)),  # ✅ Correct
        ),
        migrations.AddField(
            model_name='reservation',
            name='duree_heures',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(max_digits=8, decimal_places=2, default=0.0),
        ),
        
        # 3️⃣ Modifier le champ espace
        migrations.AlterField(
            model_name='reservation',
            name='espace',
            field=models.ForeignKey(
                to='client.Espace',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reservation',
            ),
        ),
        
        # 4️⃣ Supprimer les anciens champs
        migrations.RemoveField(
            model_name='reservation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        
        # 5️⃣ Ré-appliquer le nouveau unique_together
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('espace', 'date', 'heure_debut')},
        ),
        
        # 6️⃣ Modifier les Meta options
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'heure_debut']},
        ),
    ]