# Generated by Django 5.1.2 on 2025-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espace',
            name='type_espace',
            field=models.CharField(choices=[('petite_salle', 'Petite salle'), ('moyenne_salle', 'Moyenne salle'), ('grande_salle', 'Grande salle'), ('reunion', 'Salle de réunion'), ('brainstorming', 'Salle de brainstorming'), ('studio', 'Salle de studio'), ('espace_detente', 'Espace détente'), ('espace_formation', 'Salle de formation')], max_length=50),
        ),
    ]
