# Generated by Django 5.1.2 on 2025-12-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_reservation_notes_admin_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Méthode de paiement'),
        ),
    ]
