# Generated by Django 5.1.2 on 2025-12-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
