# Generated by Django 5.1.2 on 2025-12-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
