# Generated by Django 5.1.2 on 2025-12-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0012_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('annule', 'Annulé')], default='ouvert', max_length=20)),
                ('severite', models.CharField(blank=True, max_length=20)),
                ('estimation_remise_en_service', models.DurationField(blank=True, null=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='client.espace')),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assignes', to='client.profile')),
            ],
            options={
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='client.espace')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='tech_interface.incident')),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_assignees', to='client.profile')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
