# Generated by Django 5.1.2 on 2025-12-12 05:15

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_profile_profile_photo'),
        ('tech_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='estimation_remise_en_service',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='notes',
        ),
        migrations.AddField(
            model_name='incident',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cout_materiel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût du matériel en €', max_digits=8),
        ),
        migrations.AddField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 12, 5, 14, 2, 94245, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='materiel_utilise',
            field=models.TextField(blank=True, help_text='Liste du matériel utilisé'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='note_debut',
            field=models.TextField(blank=True, help_text='État initial constaté'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='note_fin',
            field=models.TextField(blank=True, help_text='Résultat et recommandations'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='note_intervention',
            field=models.TextField(blank=True, help_text='Actions effectuées'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='photo_apres',
            field=models.ImageField(blank=True, null=True, upload_to='interventions/apres/'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='photo_avant',
            field=models.ImageField(blank=True, null=True, upload_to='interventions/avant/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severite',
            field=models.CharField(choices=[('mineur', 'Mineur'), ('moyen', 'Moyen'), ('critique', 'Critique'), ('urgent', 'Urgent')], default='moyen', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assignes', to='client.profile'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='espace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.espace'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='incident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='tech_interface.incident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='client.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NoteIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tech_interface.intervention')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
