# Generated by Django 5.2.8 on 2025-11-24 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='statut',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salle',
            name='equipement',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
