# Generated by Django 5.1.2 on 2025-12-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_espace_alter_reservation_salle_delete_salle'),
        ('client', '0007_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_admin', to='client.espace'),
        ),
        migrations.DeleteModel(
            name='Espace',
        ),
    ]
