# Generated by Django 5.1.2 on 2025-12-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0006_alter_reservation_client_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
