# Generated by Django 5.1.2 on 2025-12-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0008_technicien_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technicien',
        ),
    ]
